/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_umBuF7Dx8', // Replace with your User Pool ID
    aws_user_pools_web_client_id: '6leobag7drbcfg01mg1q37b4g4', // Replace with your App Client ID
};

export default awsmobile;
